### ISSUE TITLE
Love this library, and jsoup is not 1.8.3

### ISSUE THREAD

**Issue by seymores** [mischov/reaver#1]
Reaver is still using version 1.8.1.
Not sure if there is any significant difference but bug fixes from jsoup would be nice update.
http://mvnrepository.com/artifact/org.jsoup/jsoup/1.8.3

Thanks for the good work.

**Comment by mischov** [comment]
Thanks for the feedback. Just pushed a version (0.1.2) to Clojars that uses 1.8.3.

Let me know if you come across any other issues, or have any suggestions.
