### ISSUE TITLE
Reddit Returns Error Code 429 (Too many requests)

### ISSUE THREAD

**Issue by msenol86** [mischov/reaver#3]
``` clojure
(slurp "https://www.reddit.com/r/clojure")

IOException Server returned HTTP response code: 429 for URL: https://www.reddit.com/r/clojure  sun.net.www.protocol.http.HttpURLConnection.getInputStream0 (HttpURLConnection.java:1839)
```

Can  we use something else than Reddit because it blocks requests. This can make things difficult for people experimenting with example on the Readme file.

I suggest https://news.ycombinator.com/ instead of Reddit

Please see my pull request

**Comment by mischov** [comment]
Fixed by PR 4. Thank you.
