### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by nathell** [mischov/reaver#6]
As [discussed on Reddit](https://old.reddit.com/r/Clojure/comments/f5pchg/ann_skyscraper_03_a_scraping_framework_that_helps/), could there be a new version that includes #5?

Thanks for Reaver!

**Comment by mischov** [comment]
Hey @nathell, I'll get a new version at as quickly as I can.

I would like to fix a few things prior to the release, like the god awful formatting and lack of tests. This will slow me down a little but I hope to have a new version out soon.

Thank you for bringing this to my attention.

**Comment by mischov** [comment]
@nathell Published 0.1.3 to Clojars.
